kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-dev-developer #Please the naming convention of "<eks-cluster>-<namespace>"
  namespace: developer #Namespace for this RoleBinding
subjects:
- kind: Group
  name: developer:dev-edit #Please stick to the naming convention of "<namespace>:<name of role>"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io